title: Aidan Kingsbury
logo: /images/Head_Shot.png
show_downloads: false
theme: jekyll-theme-minimal
description: > 
  <a href="/documents/Aidan_Kingsbury_Resume.pdf" download>Resume</a>, 
  <a href="mailto:ajkingsbury02@gmail.com">Email</a>, 
  <a href="https://www.linkedin.com/in/aidan-kingsbury-908593257/">LinkedIn</a>.
