description:
  <a href="https://akingz123.github.io/website/documents/Aidan_Kingsbury_Resume.pdf" target="_blank">Resume</a>,
  <a href="mailto:ajkingsbury02@gmail.com">Email</a>, 
  <a href="https://www.linkedin.com/in/aidan-kingsbury-908593257/">LinkedIn</a>.
title: Aidan Kingsbury
logo: /images/Head_Shot.png
theme: jekyll-theme-minimal
show_downloads: false
