title: Aidan Kingsbury
logo: /images/Head_Shot.png
show_downloads: false
theme: jekyll-theme-minimal
links:
  - title: "Download Resume"
    url: /resume.pdf
  - title: "Contact"
    url: mailto:your-email@example.com
  - title: "LinkedIn"
    url: https://www.linkedin.com/in/your-linkedin-username

