title: Aidan Kingsbury
logo: /images/Head_Shot.png
show_downloads: false
theme: jekyll-theme-minimal
description: >
  Hi, I'm Aidan Kingsbury, a student majoring in Applied Mathematics and Environmental Science. 
  You can [Download my resume](./documents/Aidan_Kingsbury_Resume.pdf), 
  [Contact me](mailto:ajkingsbury02@gmail.com), 
  or check out my [LinkedIn profile](https://www.linkedin.com/in/aidan-kingsbury-908593257/).

